# ===================================
#  Side Bar Behavior Config
# ===================================

# Record name
title: waka.utils::lang.side_bar_info.update

# Model Form Field configuration
form: $/waka/mailtoer/models/wakamailto/fields_for_side_bar.yaml

# Model Class name
modelClass: Waka\Mailtoer\Models\WakaMailto