# ===================================
#  Btn  Behavior Config
# ===================================

Description: >
    //startKeep/
modelClass: Waka\Mailtoer\Models\WakaMailto

workflow: false 

###BREADCRUMP
breadcrump:
    inSettings: true 
    indexUrl: waka/mailtoer/wakamailtos
    indexlabel: waka.mailtoer::wakamailto.title
    title: waka.mailtoer::wakamailto.form_name

###TOOL_BAR
tool_bar:
    base:
        create: 
            show: true
            permissions: [waka.mailder.admin.super]
            url: waka/mailtoer/wakamailtos/create
        reorder: 
            show: true 
            permissions: []
            url: waka/mailtoer/wakamailtos/reorder
 
        delete: 
            show: true
            permissions: [waka.mailder.admin.super]
    config_btns:
            format: all
            btns:
    config_lot:
        format: all
        btns: 
            
            lot_mail:
                config: waka.mailer::btns.lot_mail
                group: waka.utils::lang.prod.send
    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     testbtns:
    #         url: $/waka/mailtoer/controllers/wakamailtos/_test_btns.htm

###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
action_bar:
    config_btns:
        format: grouped #unique : un seul bouton, all : tts les boutons
        groups:
            waka.utils::lang.prod.produce: oc-icon-file-text-o
            waka.utils::lang.prod.send: oc-icon-external-link
            waka.utils::lang.prod.tools: oc-icon-wrench
        btns:
            duplicate:
                config: waka.utils::btns.duplicate
                group: waka.utils::lang.prod.tools
            mail:
                config: waka.mailer::btns.mail
                group: waka.utils::lang.prod.send

    # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
    #     name:
    #         url: $/waka/mailtoer/controllers/wakamailtos/_test_update.htm
Description: >
    //endKeep/


#     ##### SAUVEGARDE PURE ########

# modelClass: Waka\Mailtoer\Models\WakaMailto

# workflow: false 

# ###BREADCRUMP
# breadcrump:
#     inSettings: true 
#     indexUrl: waka/mailtoer/wakamailtos
#     indexlabel: waka.mailtoer::wakamailto.title
#     title: waka.mailtoer::wakamailto.form_name

# ###TOOL_BAR
# tool_bar:
#     base:
#         create: 
#             show: true
#             permissions: [waka.mailder.admin.super]
#             url: waka/mailtoer/wakamailtos/create
#         reorder: 
#             show: true#  
#             permissions: []
#             url: waka/mailtoer/wakamailtos/reorder
#  
#         delete: 
#             show: true
#             permissions: [waka.mailder.admin.super]
#     config_btns:
#             format: all
#             btns:
# # #     config_lot:
#         format: all
#         btns: 
# # # #             
#             lot_mail:
#                 config: waka.mailer::btns.lot_mail
#                 group: waka.utils::lang.prod.send
# #     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     testbtns:
#     #         url: $/waka/mailtoer/controllers/wakamailtos/_test_btns.htm

# ###ACTION_BAR Producteurs. Les behavior liée aux boutons doivent êtres instanciés implements = [waka.xxx.behaviors.yyy] dans le controller. 
# action_bar:
#     config_btns:
#         format: grouped #unique : un seul bouton, all : tts les boutons
#         groups:
#             waka.utils::lang.prod.produce: oc-icon-file-text-o
#             waka.utils::lang.prod.send: oc-icon-external-link
#             waka.utils::lang.prod.tools: oc-icon-wrench
#         btns:
# # # # # #             duplicate:
#                 config: waka.utils::btns.duplicate
#                 group: waka.utils::lang.prod.tools
# # #             mail:
#                 config: waka.mailer::btns.mail
#                 group: waka.utils::lang.prod.send
# # # # # 
#     # partials: #Attention seul les variables modelId et modelClass (class du controller) sont disponible sans les partials.  
#     #     name:
#     #         url: $/waka/mailtoer/controllers/wakamailtos/_test_update.htm
