# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Document

# Model Class name
modelClass: Waka\Mailtoer\Models\WakaMailto
type: email
text_info: "Glissez une valeur dans la zone de saisie"





