# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.mailtoer::wakamailto.form_name

# Model Form Field configuration
form: $/waka/mailtoer/models/wakamailto/fields.yaml

# Model Class name
modelClass: Waka\Mailtoer\Models\WakaMailto

# Default redirect location
defaultRedirect: waka/mailtoer/wakamailtos

# Create page
create:
    title: waka.mailtoer::wakamailto.create
    redirect: waka/mailtoer/wakamailtos/update/:id
    redirectClose: waka/mailtoer/wakamailtos
    form: $/waka/mailtoer/models/wakamailto/fields_create.yaml

# Update page
update:
    title: waka.mailtoer::wakamailto.update
    redirect: waka/mailtoer/wakamailtos/update/:id
    redirectClose: waka/mailtoer/wakamailtos

# Preview page
preview:
    title: waka.mailtoer::wakamailto.preview_name
